Update SimpleStorage.sol
pragma solidity 0.8.8;
 do not compile.

Description:

ParserError: Source file requires different compiler version (current compiler is 0.8.26+commit.8a97fa7a.Emscripten.clang) - note that nightly builds are considered to be strictly less than the released version
 --> contracts/SimpleStorage.sol:4:1:
  |
4 | pragma solidity 0.8.8;